export default {
  robot: {
    panelLiveDash: {
      updatePrimitiveData: '',
      extensionCommonPrimitives: [
        'addNode',
        'removeNode',
        'addEdge',
        'removeEdge',
        'workspacePrimitives',
      ],
      extensionComplexPrimitives: [
        'addNode',
        'removeNode',
        'addEdge',
        'removeEdge',
        'workspacePrimitives',
      ],
    },
    storageSystem: [
      'addRecord',
      'putRecord',
      'hasRecord',
      'getRecord',
      'removeRecord',
      'clearStorage',
    ],
    eventSystem: [
      'createEvent',
      'createAndPublish',
      'createAction',
      'registerAction',
      'subscribeByNames',
      'subscribeEventNameByCallback',
      'subscribe',
      'subscribeEventsByName',
      'createActionByCallback',
      'findActionById',
      'findEventById',
      'findEventsByName',
      'findActionsByName',
      'showAvailableEvents',
      'showAvailableActions',
    ],
    interactionSystem: ['get', 'post', 'put', 'patch', 'delete'],
    styleSystem: ['setTheme', 'setDesignVariables'],
  },
};
